version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
     commands:
      - echo Build completed on `date`
artifacts:
  files:
      - '**/*'
  base-directory: 'dist/angular_devops*'
  discard-paths: yes
